### ISSUE TITLE
Automatic FLO-2D map layout

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#12]
- [x] A4 map portrait & landscape
- [x] A3 map portrait & landscape

**Comment by rpachaly** [comment]
Inspired by http://qgis-hub.fast-page.org/layouts.php

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/bde58643-6dc5-4208-8df4-baccea23bfbf)

**Comment by rpachaly** [comment]
Very good plugin. We can take some ideas/code snippets from it.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/3a73aae6-c0ed-4f19-994f-61cc59d27028)

**Comment by FLO-2DKaren** [comment]
You can stretch the legend on these pretty easy.  You can take out the label Band and stretch it a bit.  That editor for the legend properties is very robust.

**Comment by rpachaly** [comment]
I added a tab for FLO-2D Layouts. I'm trying to add stuff to map automatically. 

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/c57ee2ae-0265-453f-8e8a-3d55fbe2b189)

**Comment by rpachaly** [comment]
@FLO-2DKaren 

Take a look on the branch [layout_composer](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/tree/layout_composer). I did not merge it. See if you like.

**Comment by FLO-2DKaren** [comment]
I just got it and I'm looking at it now.

**Comment by FLO-2DKaren** [comment]
The scale bar on the first A4 layout is overlapping other layers
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/98f16a55-b59e-4ab7-b137-87b66897f67d)
 
You might not be seeing this on your screen.  I wonder if it's because I'm zoomed to a weird level.

**Comment by rpachaly** [comment]
I'm aware of that. I think that creating a perfect automatic layout is almost impossible because every project will have different scales and data. Small adjustments must be done by the users. That's the reason that I removed the automatic legend. I don't know that the user would like to show.

**Comment by FLO-2DKaren** [comment]
I'm going to close this issue because the tool is OK for release.  I've used it on several projects without any issues.  Any new development can be added on a new issue.
