### ISSUE TITLE
add these maps for generic mapping

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#14]
I'm moving this here from another repository.
We should review this and what Mapper has to flesh out this list.
I also think we could group them into like maps on the Plugin Layout

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/f95c3e06-375b-4671-a079-04c399155884)

**Comment by rpachaly** [comment]
Something that would be nice for me is to have projects that have these processes (infiltration, channels, storm drain, etc)
