### ISSUE TITLE
Other maps that we currently map

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#15]
Ground Elevation
Water Surface Elevation
Depth
Final Depth
Combined Depth
Final Combined Depth
Channel depth
Final Channel Depth
Street Depth

Max Velocity
Max Velocity Vector
Final Velocity
Max channel velocity (This one might not be good because it only maps the left bank)
Street velocity (Not 100 percent useful because people don't use streets anymore.)

Duration of inundation
Impact Force
Static Pressure
Specific Energy
Levee Deficit

Time to 1ft
Time to 2ft
Time to Max

Various types of hazard
Swiss
BOR
Australian
Austrian
FEMA

**Comment by rpachaly** [comment]
Closing in favor of #13
