### ISSUE TITLE
floodwave arrival time 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#16]
@rpachaly 
Hi Robson,  It took me a while to figure out a nice look for time mapping but since a lot of problematic mapping happens wihtin minutes, I developed a map color scheme that works well for tailings dams.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/b33e258d-310d-4cf7-a9b2-670c39c4bf8f)

Here is how I set up the color scheme where anything over 2 to 3 hours is red and the shorter duration times are disretely mapped.

**Comment by FLO-2DKaren** [comment]
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/8e4d3388-2f60-4a24-802b-b16830aee903)

**Comment by rpachaly** [comment]
> ![image](https://user-images.githubusercontent.com/20424460/271791171-8e4d3388-2f60-4a24-802b-b16830aee903.png)

Quick question. Don't you think that it would be better to have the reds on shorter times and green in longer times?

**Comment by rpachaly** [comment]
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/3c80f07a-e2b7-4350-a540-ca780bc4bc17)

**Comment by FLO-2DKaren** [comment]
Yes.  Sorry about that.  I didn't reverse the color pattern.

**Comment by rpachaly** [comment]
Ok, this is done. I'm pushing the branch and closing the issue.
