### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#17]
We need to start a documentation for MapCrafter.

**Comment by FLO-2DKaren** [comment]
Do you want to use the Wiki pages or do you want to follow the FLO-2D plugin and publish the documentation to github.io website.  https://flo-2dsoftware.github.io/qgis-flo-2d-plugin/

The wiki is markdown and the other one is rst.

**Comment by rpachaly** [comment]
I like the Wiki pages but isn't it better to follow the same FLO-2D standard?

**Comment by FLO-2DKaren** [comment]
Wiki might be easier since you don't have to add the conversion code from sphinx.
I don't like how the FLO-2D uses Dark Mode.  But I bet we can fix that.

**Comment by rpachaly** [comment]
Ok, I'll start with wiki. If we need to change later we'll have the most difficult part - writing everything - done.

**Comment by rpachaly** [comment]
I'm going to close this one. If we need to add anything more complex to documentation, we create another issue.
