### ISSUE TITLE
Vector Map can't find svg

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#22]
I'm getting this for the vector map.
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/a7cc157a-44ad-42c3-902b-588318882411)

Maybe it's because my svg arrows aren't selectable
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/3bb6142c-a643-461d-af4d-2f3172de31f2)

**Comment by rpachaly** [comment]
The SVG files were not uploaded when I pushed the branch before. I uploaded it again and it should be working now.
