### ISSUE TITLE
Raster Style Ideas

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#29]
The most important issue is to see if we can sort out the style manager.  I think we can fix this with the qgs data and the rasterrenderer mods

I believe that rasterrenderer is not applying the min max correctly in the *.qgs file.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/ae302b5f-8ce0-4be6-bc84-3e93bb15221b)

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/493594d5-c43b-408e-8fb0-fdec706a6aa2)

`        <rasterrenderer classificationMax="nan" nodataColor="" classificationMin="nan" band="1" opacity="1" alphaBand="-1" type="singlebandpseudocolor">
          <minMaxOrigin>
            <limits>None</limits>
            <extent>WholeRaster</extent>
            <statAccuracy>Estimated</statAccuracy>
            <cumulativeCutLower>0.02</cumulativeCutLower>
            <cumulativeCutUpper>0.98</cumulativeCutUpper>
            <stdDevFactor>2</stdDevFactor>
          </minMaxOrigin>
          <rastershader>
            <colorrampshader classificationMode="1" minimumValue="nan" labelPrecision="6" colorRampType="INTERPOLATED" clip="1" maximumValue="nan">
              <item color="#ffffff" alpha="255" label="" value="0.01"/>
              <item color="#add8e6" alpha="255" label="" value="7.108700160980225"/>
              <item color="#0000ff" alpha="255" label="" value="14.20740032196045"/>
              <rampLegendSettings minimumLabel="" suffix="" orientation="2" direction="0" prefix="" maximumLabel="" useContinuousLegend="1">
                <numericFormat id="basic">
                  <Option type="Map">
                    <Option name="decimal_separator" type="invalid"/>
                    <Option name="decimals" value="6" type="int"/>
                    <Option name="rounding_type" value="0" type="int"/>
                    <Option name="show_plus" value="false" type="bool"/>
                    <Option name="show_thousand_separator" value="true" type="bool"/>
                    <Option name="show_trailing_zeros" value="false" type="bool"/>
                    <Option name="thousand_separator" type="invalid"/>
                  </Option>
                </numericFormat>
              </rampLegendSettings>
            </colorrampshader>
          </rastershader>
        </rasterrenderer>`

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/issues/26#issuecomment-1789256092_

**Comment by FLO-2DKaren** [comment]
When I extracted the QGZ file, I got this little db file. It might be something we can use to sort out our styles easier.
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/478742ca-e726-4725-8688-686a1dc741e5)

**Comment by rpachaly** [comment]
#39
