### ISSUE TITLE
FEMA Dam Safety mapping

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#3]
For the future ideas
[fema_dam-safety_inundation-mapping-flood-risks.pdf](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/files/12716212/fema_dam-safety_inundation-mapping-flood-risks.pdf)

**Comment by rpachaly** [comment]
Closing in favor of #13
