### ISSUE TITLE
Initial View

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#30]
Set the Initial view to uncheck all but elevation.
That will speed up loading and users won't have to uncheck all of the layers.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/577a899b-0fd1-426d-bd01-925a5d5d3ebb)

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/issues/26#issuecomment-1789261807_

**Comment by rpachaly** [comment]
I'm also going to try to add them collapsed.

**Comment by FLO-2DKaren** [comment]
You can see the flags pretty clearly in the qgs file.  I think that would be easy to set with the iface utilities.

**Comment by rpachaly** [comment]
Just finished it here. It is in this [commit](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/commit/67a2505f707c5fc00574d678dd130887347a1e1b)
