### ISSUE TITLE
Group Layers

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#31]
Group layers by map crafter groups
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/dbd5092e-d311-4c76-8c3e-85c9aa9964a5)

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/issues/26#issuecomment-1789264174_

**Comment by rpachaly** [comment]
Done on [commit](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/commit/af5b05b3fc914c588433d428ef8f1b2fc870d5bc)
