### ISSUE TITLE
Hidden window

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#32]
When I click MapCrafter button, the window stays hidden behind QGIS.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/646b8c67-055e-4074-ac1b-1aa895739129)

_Originally posted by @FLO-2DKaren in https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/issues/26#issuecomment-1789272616_

**Comment by FLO-2DKaren** [comment]
So I think the easy fix for this one is after the window is opened set it to the top position.

**Comment by rpachaly** [comment]
When does this happen? When opening MapCrafter the first time? For me it does not happen.

**Comment by FLO-2DKaren** [comment]
Open MapCrafter
Then click anywhere on the QGIS window to bring it to the top view.
Then click the Open MapCrafter button and it stays on the below QGIS.

**Comment by FLO-2DKaren** [comment]
I think a simple Bring to Front on the open MapCrafter code would do the trick.

**Comment by FLO-2DKaren** [comment]
If it's not broken on your system.  Close the window.  It's not important enough to spend to much time on.

**Comment by rpachaly** [comment]
Got it! I was able to reproduce it here. I'm calling it a day right now but tomorrow I'll have it fixed.

**Comment by rpachaly** [comment]
Done on [commit](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/commit/560da6f8d020105fecb9cb416c9710ff3968b326)
