### ISSUE TITLE
Add counter/id identifier 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#38]

**Comment by rpachaly** [comment]
Noemi:

2. Be able to load output from different scenarios in one QGIS  project. I get a python error when I try to load more scenarios with Mapcrafter, even after renaming the existing layer in QGIS.

**Comment by rpachaly** [comment]
This one was tricky but I think the code is now very robust. Needs to be tested thoroughly. Done on [commit](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/commit/35131a946d9959d6ce7914f8fa25b49ede4d22d6).

**Comment by FLO-2DKaren** [comment]
I tested this with my basin test.  Seems to be working very good.
