### ISSUE TITLE
Simbology missing in Layers panel after loading previous project

### ISSUE THREAD

**Issue by FLO-2DJJ** [FLO-2DSoftware/FLO-2DMapCrafter#39]
When a project is loaded after having saved it with some MapCrafter layers, the symbologies are missing in the Layers panel:

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424575/f34425db-7cc8-403d-bbf8-b4f3a452cdbb)

I'm using the new_mapping branch.

The symbology can be restored using the **Properties...Symbology** but, Can they be done automatically on loading?

**Comment by rpachaly** [comment]
#29

**Comment by rpachaly** [comment]
Ok, I think this is solved and the code is way more elegant. But it needs to be tested again. 

The symbology is saved on the Layer Properties and when we close and reopen a project. 

It passed all my tests. 

Check [commit](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/commit/a85d122336dcbb762f86a92f874cc720497c426c)

**Comment by FLO-2DKaren** [comment]
I'm closing this because Robson closed #29.  They are the same.  If something new comes up, we can create a new issue.
