### ISSUE TITLE
Groups added when not used

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#40]
Noemi tested this yesterday.  When you only want one map, all of the groups are added.  Might want to sort that out.

**Comment by rpachaly** [comment]
Noemi sent me an email about this issue. I've just fixed it on [commit](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/commit/7622c1846a4043173dcee9d7e01fd94d3a25c56c).
