### ISSUE TITLE
Some Layers still expanded

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#41]
Some layers are still expanded.  I think you fixed this on issue #30.  
If you think it's complete, go ahead and close this issue.  I am trying to stay on the latest branch but I could be a little behind.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/0676f0a9-5a6f-4be3-8424-1e5b92df1f7b)

**Comment by FLO-2DKaren** [comment]
New information.  The expanded layers only happen when the new Project ID field is applied.

**Comment by FLO-2DKaren** [comment]
Looks like its only time and velcoity vectors that are expanded.

**Comment by rpachaly** [comment]
I was trying to fix the style issue but it looks more complicated than I expected. I'm going to fix this one first and then go back to the styles.

**Comment by rpachaly** [comment]
I'm not able to reproduce this bug. All maps are not expanded. Can you send me your project?

**Comment by FLO-2DKaren** [comment]
Hi Robson,  

This is not a critical issue so you can leave it for later if you want to.

**Comment by FLO-2DKaren** [comment]
Oh I'm behind on the comment section.  If you can't reproduce this I'm going to close it.
