### ISSUE TITLE
Levee Freeboard Deficiency 

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#43]
Levee freeboard deficit is reported in the output file LEVEEDEFIC.OUT. 
Five levels of freeboard deficit are listed in the file as follows:
Levels, Definition
0, freeboard > 3 ft
1, 2 ft < freeboard < 3 ft
2, 1 ft < freeboard < 2 ft
3, freeboard < 1 ft
4, levee overtopped

Future development idea for the style.  This is like a hazard or warning so we should use colors and labels that represent high water on a levee or wall.

0 white
1 yellow 
2 yellow-orange
3 orange
4 red

A Project For Testing 
https://flo-2d.sharefile.com/d-s062870799aa34e91be99363f1ce1291d

**Comment by FLO-2DKaren** [comment]
Cool,  I put that info in the Wiki too so this is nice.  I think I'll wait to test this because I wan to test the min value issue at the same time.

**Comment by rpachaly** [comment]
I'm reopening this just to ask a question:
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/b7844176-5a8c-4fd7-9cf0-7ce73af46d04)

Should I keep the symbology like this or add a full opacity instead of white for 0s?

**Comment by rpachaly** [comment]
I prefer with transparency.
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/f7c02d87-d37b-422c-b6e5-e5f6b26ecf13)

**Comment by FLO-2DKaren** [comment]
Me too.

**Comment by rpachaly** [comment]
Ok. I'm going to close this branch again.
