### ISSUE TITLE
Min Value No Data

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#47]
Min value set to no data.

Here's the test file
[FINALDEP.zip](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/files/13268394/FINALDEP.zip)

This is also posted on Rasterizor but the color scheme there is different so I'm posting it here too since this color scheme looks odd.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/e483b238-32cf-47a3-a6b2-6053ca930cc8)

**Comment by rpachaly** [comment]
I have to solve the time variables before pushing this branch. 

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/abe5aa1a-8165-4ea4-8e12-31d2187db639)

**Comment by rpachaly** [comment]
And ARR hazard map
![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/4b059140-eb35-4c3a-a308-e51e272483bb)

**Comment by rpachaly** [comment]
I used a more generic style for time variables:

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/67e243a3-3d5f-415a-bb0a-27f52dfd4cd2)

**Comment by rpachaly** [comment]
I pushed the branch.
