### ISSUE TITLE
CRS Lat Long

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#49]
Copying an idea from Rasterizor.
Since a FLO-2D project shouldn't be created in LatLong coordinate system, we should query for a new system if the project is set to epsg 4326.

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/75

**Comment by FLO-2DKaren** [comment]
Seems to be working OK.
