### ISSUE TITLE
Unnecessary Files

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#51]
These are the things I don't think are necessary to be shared with Git.  Some of these things are necessary for building or updating the plugin but not for GIT.  My thought it keep it as simple as possible so when we move forward with updates, we have fewer things to have conflicts.

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/20424460/a5b37e7e-d6dd-4b56-96b4-433a1710982d)

**Comment by FLO-2DKaren** [comment]
@rpachaly 

Keep your source repository in good shape: 

- [ ] No generated files left in the repository (ui_*.py, gen. help files…).
- [ ] No __MACOSX, .git, __pycache__ or other hidden directories
- [ ] Good code organization (subfolders).
- [ ] Code comments are available.
- [ ] PEP8 & Python/QGIS guidelines compliance.
- [ ] A README file and a LICENCE file are present.
- [ ] If some dependencies are not available in OSGeo4w Python, provide instructions on how to install them on Windows.
- [ ] The name of the plugin and the folder name do not repeat the word `plugin`.

**Comment by rpachaly** [comment]
@FLO-2DKaren I think MapCrafter has all requirements. I removed the unnecessary files and added the README and LICENSE.
