### ISSUE TITLE
License text and license file.

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#54]
Add this to the end of the readme

## FLO-2D Rasterizor license

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <https://www.gnu.org/licenses/>.

We may also need to put the readme.md into the plugin file so people can see this.

**Comment by rpachaly** [comment]
Added on [merge](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/commit/753c308401aefb4d088fdd64312686020239cafc).
