### ISSUE TITLE
Maximum Scour 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#56]
The symbology for maximum scour and final bed difference are not correct

**Comment by rpachaly** [comment]
@FLO-2DKaren Which output files may have negative values? I was setting a minimum of 0.01 but this may not be the case for all outputs.

**Comment by rpachaly** [comment]
It was just symbology adjustments. I merged on [branch](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/tree/min_symbology)

**Comment by FLO-2DKaren** [comment]
Ooooh good point.  If an elevation or a water surface is below sea level, it can also be negative but I don't think you would limit that in the same way as depth on in this case change in bed elevation so for now, this is the only one I can think of.  Keep it closed.  I'll get it all tested tomorrow.
