### ISSUE TITLE
ToolTips units

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#61]
Add units to the tooltips 

-> Consider adding the tooltips directly on the code bc is easier to fix.

**Comment by FLO-2DKaren** [comment]
If you do one, I can do the rest.

**Comment by FLO-2DKaren** [comment]
@rpachaly 
I've been adding the info from the Data Input manual.  Sometimes it's really helpful to see that in a tooltip.  I did it for the Global parameter for Green Ampt.  But I didn't add them to the code.  I probably put it on the *.ui file.

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/71
