### ISSUE TITLE
Multiple total inflow discharge plots 

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#67]
Gds reads the SWMM.rpt and creates a folder with name including date and time with the discharge plots for all the SD features

It should be on the SD manual

**Comment by FLO-2DNoemi** [comment]
We are not installing GDS anymore so I think it will be better to add to
the SD manual the new plotting feature that we will add to the plugin.
Hopefully we will be able to have it ready by mid year.

**Comment by rpachaly** [comment]
Still a lot to do, but here is a preview. 

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/1418b100-e4dc-432f-8c44-40b7b5b0a5c1)

![I1-35-31-18_Node Depth](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/9f660c0a-6582-4d33-b836-cd1e62713985)

**Comment by FLO-2DKaren** [comment]
Robson,

Can you name them like this?

name_gridelement_node.png

1. It's hard to filter search them or sort them if node is first.
2. It's harder to find the name than the grid element number when you are going back and forth through data.

**Comment by rpachaly** [comment]
Hi Karen, 

I'm afraid that the grid number will be difficult to add because I'm using the INP & RPT files to create the plots. But I'll figure it out and try to add the grid number.

**Comment by rpachaly** [comment]
Ok, I've an idea here.

**Comment by rpachaly** [comment]
https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/96178c99-1e87-4808-a234-d57347680a9c

**Comment by rpachaly** [comment]
Done on #68.

Final layout

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/28fc8208-46ad-48a8-a6ce-1ff5a823d2ab)

**Comment by FLO-2DKaren** [comment]
I think all is working OK.  I'm going to close this.
