### ISSUE TITLE
MapCrafter folder issue

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#69]
https://github.com/FLO-2DSoftware/qgis-flo-2d-plugin/issues/1342#issuecomment-2127249121

**Comment by FLO-2DKaren** [comment]
I haven't experienced the folder issue in a long time.  I believe it was related to my method.

**Comment by rpachaly** [comment]
Let's close this issue then. If we face this again, we can open a new issue.
