### ISSUE TITLE
Layer Grouping

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#7]
Group the layers based on the type of map.

**Comment by rpachaly** [comment]
@FLO-2DKaren 

It is still a little buggy, but this is what you were expecting right?

![image](https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/assets/39889306/f160debd-b282-4687-aa1b-882790785da8)

**Comment by FLO-2DKaren** [comment]
That will work for now.  We'll want to make some other groups and such when we expand the tool for generic mapping.

**Comment by rpachaly** [comment]
Closed with #8
