### ISSUE TITLE
Import geopandas error

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#76]

**Comment by rpachaly** [comment]
Create a new profile and install mapcrafter

**Comment by FLO-2DKaren** [comment]
Update meta data and readme about the dependencies per the QGIS Plugin recommendations.
Do we want to notify swmmio about the deprecation warnings?  I'm sure they know but sometimes those sit in that pond and get old.  Like Profile Tool!!!

**Comment by rpachaly** [comment]
I removed the geopandas and we`re using the QgsVectorFileWriter. So, this error is gone. On https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/tree/deprecation-warning

**Comment by FLO-2DKaren** [comment]
No issues with this.
