### ISSUE TITLE
Remove Profile code

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#78]
![image](https://github.com/user-attachments/assets/93a9eaba-5d49-4e08-86c0-2b30af2ed583)

**Comment by rpachaly** [comment]
Done & merged on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/81

**Comment by FLO-2DKaren** [comment]
No issues noted with removing this.
