### ISSUE TITLE
Odd path error

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#85]
2024-09-10T12:07:26     WARNING    [Errno 13] Permission denied: 'C:\\HoursFlooded_0.0.png'

**Comment by rpachaly** [comment]
There was a path error on the HoursFlooded. I was not seeing this bug because my projects are on the D drive. It is fixed and merged on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/90

**Comment by FLO-2DKaren** [comment]
No more errors.  I updated swmmio.
