### ISSUE TITLE
Videos showing testing

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#86]
### MapCrafter Test:
https://github.com/user-attachments/assets/7e6ef3bb-e8b9-4cbd-a4c0-8ede620750b7

### Storm drain test
https://github.com/user-attachments/assets/799977d2-ea0f-434d-8956-26f3cfd7cd5d

**Comment by rpachaly** [comment]
I can't reproduce the bugs on my projects here. Can you share your testing data with me?

**Comment by FLO-2DKaren** [comment]
It's just the self help kit with the simple storm drain.  I'm on QGIS 3.38.
https://flo-2d.sharefile.com/d-s61bbe33285c84d75ab2f65e6df37f670
Here's the completed project with the MapCrafter folder in it.  Give it 15 min to upload but I assume you are already finished today.  Sorry I didn't see this in time.
