### ISSUE TITLE
CRS selector bug

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#92]
Hi Robson,  I got this image from an end user.  They are running QGIS 3.28.

![image](https://github.com/user-attachments/assets/b1fe1837-4e7a-4e31-8252-be6ca6cc022f)

**Comment by rpachaly** [comment]
I installed QGIS 3.28-14 and I got the error. It was an unused import. It is fixed and merged on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/93

I think this was the error that I was getting when trying to test the plugin on a linux docker. 

It is the second time this month that I got an error related to a library that is imported and not used. We should remove the imported and unused libraries for a good code maintenance. I'll create an issue on this.
