### ISSUE TITLE
Remove unused libraries

### ISSUE THREAD

**Issue by rpachaly** [FLO-2DSoftware/FLO-2DMapCrafter#94]

**Comment by rpachaly** [comment]
Done and merged on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/95

**Comment by FLO-2DKaren** [comment]
OK, I'll test this thoroughly with all types of projects.

**Comment by FLO-2DKaren** [comment]
I tested all 3 types of project mapping and no bugs came out but I'm not testing on an old QGIS so we'll see how it goes.
