### ISSUE TITLE
Velocity Vectors on QGIS 3.34.11

### ISSUE THREAD

**Issue by FLO-2DKaren** [FLO-2DSoftware/FLO-2DMapCrafter#99]
2024-10-07T16:01:50     INFO    Application state:
             QGIS_PREFIX_PATH env var: C:/OSGeo4W/apps/qgis-ltr
             Prefix: C:/OSGeo4W/apps/qgis-ltr
             Plugin Path: C:/OSGeo4W/apps/qgis-ltr/plugins
             Package Data Path: C:/OSGeo4W/apps/qgis-ltr/.
             Active Theme Name: default
             Active Theme Path: C:/OSGeo4W/apps/qgis-ltr/./resources/themes\default\icons/
             Default Theme Path: :/images/themes/default/
             SVG Search Paths: C:/OSGeo4W/apps/qgis-ltr/./svg/
              C:/Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/svg/
              C:/OSGeo4W/apps/qgis/./svg/
             User DB Path: C:/OSGeo4W/apps/qgis-ltr/./resources/qgis.db
             Auth DB Path: C:/Users/Karen/AppData/Roaming/QGIS/QGIS3\profiles\default/qgis-auth.db
             
2024-10-07T16:02:24     WARNING    QgsField(): arguments did not match any overloaded call:
              overload 1: argument 2 has unexpected type 'Type'
              overload 2: argument 1 has unexpected type 'str'

https://github.com/user-attachments/assets/dc5afe51-548f-4424-9d3e-ed8ebf626654

**Comment by rpachaly** [comment]
Hi Karen, I was able to reproduce this bug. This error is caused on how the QgsField is constructed. 

On recent versions of QGIS it was tagged as deprecated (see this comment https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/issues/77#issuecomment-2334226085). We already fixed this deprecation warning on latest QGIS versions. I'll add a try/exception block to make it to work on both constructors (old and new).

**Comment by rpachaly** [comment]
It is done and tested on https://github.com/FLO-2DSoftware/FLO-2DMapCrafter/pull/100

It is working, but we should recommend our client to update to more recent QGIS versions.

**Comment by FLO-2DKaren** [comment]
I will make an installer packages for both because we still have lots of plug-in 115 users who can't update right now.

**Comment by rpachaly** [comment]
Don't bother with that. It should work fine on both versions now.

**Comment by FLO-2DKaren** [comment]
right I didn't mean MapCrafter package
